"""First

Revision ID: 7a1c96ed3fad
Revises: 
Create Date: 2023-10-20 18:45:20.340474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a1c96ed3fad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('publish_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ADMIN', native_enum=False), server_default='USER', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media',
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('media_type', sa.Enum('video', 'photo', native_enum=False), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('file_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media')
    op.drop_table('users')
    op.drop_table('events')
    op.drop_table('channels')
    # ### end Alembic commands ###
